###################### Printig turtle 



import turtle
from turtle import Turtle, Screen
import random
dagi = Turtle()
screen = Screen()
turtle.colormode(255)
color_list = [(202,164,109), (238,232,170), (138,226,52), (153,69,18), (152,251,152), (255,20,147), (255,165,0), (255,69,0), (106,90,205), (67,207,209)]

# dagi.penup()
# dagi.hideturtle()
dagi.setheading(130)
dagi.forward(250)
dagi.setheading(0)
num_dots = 100

for count in range(1, num_dots + 1):
    dagi.dot(20, random.choice(color_list))
    dagi.forward(50)

    if count % 10 == 0:
        dagi.setheading(270)
        dagi.forward(50)
        dagi.setheading(180)
        dagi.forward(500)
        dagi.setheading(0)






##################### Day 18
# turtle.colormode(255)
# dagi.speed("fastest")
# screen.bgcolor("black")
# screen.title("color")
# def random_color():
#     r = random.randint(0, 255)
#     g = random.randint(0, 255)
#     b = random.randint(0, 255)
#     random_color = (r, g, b)
#     return  random_color
# for _ in range(100):
#     dagi.color(random_color())
#     dagi.circle(100)
#     dagi.setheading(dagi.heading() + 10)

screen.exitonclick()
# #################### angels Day
# num_side = 0
# def sides(num_side):
#     angels = 360 / num_side
#     for _ in range(num_side):
#         dagi.forward(100)
#         dagi.right(angels)
# for side in range(3, 13):
#     sides(side)
# sides(3)
# sides(4)
# sides(5)
# sides(6)
# sides(7)
# sides(8)
# sides(9)
# sides(10)
# sides(11)
# sides(12)




######################### angels me
# dagi.shape("turtle")
# dagi.color("red")
# dagi.fillcolor("gray")
# dagi.speed(3)
# def triangle():
#     dagi.color("green")
#     dagi.forward(70)
#     dagi.right(120)
#     dagi.forward(70)
#     dagi.right(120)
#     dagi.forward(70)
#     dagi.right(120)
# def square():
#     dagi.color("blue")
#     dagi.forward(70)
#     dagi.right(90)
#     dagi.forward(70)
#     dagi.right(90)
#     dagi.forward(70)
#     dagi.right(90)
#     dagi.forward(70)
#     dagi.right(90)
# def pentagon():
#     dagi.color("black")
#     dagi.forward(70)
#     dagi.right(72)
#     dagi.forward(70)
#     dagi.right(72)
#     dagi.forward(70)
#     dagi.right(72)
#     dagi.forward(70)
#     dagi.right(72)
#     dagi.forward(70)
#     dagi.right(72)
# def hexagon():
#     dagi.color("gray")
#     dagi.forward(70)
#     dagi.right(60)
#     dagi.forward(70)
#     dagi.right(60)
#     dagi.forward(70)
#     dagi.right(60)
#     dagi.forward(70)
#     dagi.right(60)
#     dagi.forward(70)
#     dagi.right(60)
#     dagi.forward(70)
#     dagi.right(60)
# def heptagon():
#     dagi.color("red")
#     dagi.forward(70)
#     dagi.right(51.4)
#     dagi.forward(70)
#     dagi.right(51.4)
#     dagi.forward(70)
#     dagi.right(51.4)
#     dagi.forward(70)
#     dagi.right(51.4)
#     dagi.forward(70)
#     dagi.right(51.4)
#     dagi.forward(70)
#     dagi.right(51.4)
#     dagi.forward(70)
#     dagi.right(51.4)
# def octagon():
#     dagi.color("blue")
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
#     dagi.right(45)
#     dagi.forward(70)
# def ninagon():
#     dagi.color("black")
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
#     dagi.right(40)
#     dagi.forward(70)
# def decagon():
#     dagi.color("blue")
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
#     dagi.right(36)
#     dagi.forward(70)
# triangle()
# square()
# pentagon()
# hexagon()
# heptagon()
# octagon()
# ninagon()
# decagon()

# def pen():
#     dagi.forward(10)
#     dagi.penup()
#     dagi.forward(10)
#     dagi.pendown()
#     dagi.forward(10)
#     dagi.penup()
#     dagi.forward(10)
#     dagi.pendown()
#     dagi.forward(10)
#     dagi.penup()
#     dagi.forward(10)
#     dagi.pendown()
#     dagi.forward(10)
#     dagi.penup()
#     dagi.forward(10)
#     dagi.pendown()
# pen()
# dagi.speed(2)
# def go():
#     dagi.right(90)
#     dagi.forward(100)
#     dagi.right(90)
#     dagi.forward(100)
#     dagi.right(90)
#     dagi.forward(200)
#     dagi.right(90)
#     dagi.forward(200)
#     dagi.right(90)
#     dagi.forward(300)
#     dagi.right(90)
#     dagi.forward(300)
#     dagi.right(90)
#     dagi.forward(400)
#     dagi.right(90)
#     dagi.forward(400)
#     dagi.right(90)
#     dagi.forward(500)
# go()
# screen.exitonclick()
